name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        shell: bash


      - name: Running httpx to check top all ports
        run: |
          subfinder -dL input/target.txt -o output/subdomain.txt | tee output/subdomain.txt
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/subdomain.txt -title -nc -t 300 -p 80,443,8080,8443,8090,9090 -silent -o output/httpx.txt | tee output/httpx.txt
        shell: bash
        
      - name: Running nuclei scaning
        run: |
          nuclei -l output/httpx.txt -o output/vuln.txt | tee output/vuln.txt
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/subdomain.txt
          git add output/httpx.txt
          git add output/vuln.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "hoonty233@gmail.com.org"
          git config --global user.name "hoonty233"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
